# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := mod_spdy
DEFS_Debug := \
	'-D_LARGEFILE64_SOURCE' \
	'-DHAVE_CONFIG_H' \
	'-DLINUX=2' \
	'-D_REENTRANT' \
	'-D_GNU_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	 \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-std=gnu++0x \
	-fPIC \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := \
	-Ithird_party/chromium/src \
	-I. \
	-I$(obj)/gen \
	-Ithird_party/apache/httpd/src/include \
	-Ithird_party/apache/httpd/src/os/unix \
	-Ithird_party/apache/httpd/gen/arch/linux/x64/include \
	-Ithird_party/apache/apr/src/include \
	-Ithird_party/apache/apr/src/include/arch/unix \
	-Ithird_party/apache/apr/gen/arch/linux/x64/include \
	-Ithird_party/apache/aprutil/src/include \
	-Ithird_party/apache/aprutil/gen/arch/linux/x64/include

DEFS_Release := \
	'-D_LARGEFILE64_SOURCE' \
	'-DHAVE_CONFIG_H' \
	'-DLINUX=2' \
	'-D_REENTRANT' \
	'-D_GNU_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := \
	 \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-std=gnu++0x \
	-fPIC \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := \
	-Ithird_party/chromium/src \
	-I. \
	-I$(obj)/gen \
	-Ithird_party/apache/httpd/src/include \
	-Ithird_party/apache/httpd/src/os/unix \
	-Ithird_party/apache/httpd/gen/arch/linux/x64/include \
	-Ithird_party/apache/apr/src/include \
	-Ithird_party/apache/apr/src/include/arch/unix \
	-Ithird_party/apache/apr/gen/arch/linux/x64/include \
	-Ithird_party/apache/aprutil/src/include \
	-Ithird_party/apache/aprutil/gen/arch/linux/x64/include

OBJS := \
	$(obj).target/$(TARGET)/mod_spdy/mod_spdy.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/mod_spdy/libspdy_apache.a $(obj).target/base/libbase.a $(obj).target/build/mod_spdy_version_header.stamp $(obj).target/net/libspdy.a $(obj).target/third_party/apache/httpd/include.stamp $(obj).target/mod_spdy/libspdy_common.a $(obj).target/base/libbase_static.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/third_party/chromium/src/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/build/lastchange.stamp $(obj).target/net/libinstaweb_util.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/third_party/apache/apr/include.stamp $(obj).target/third_party/apache/aprutil/include.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := \
	-pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	-lrt

$(obj).target/mod_spdy/libmod_spdy.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/mod_spdy/libmod_spdy.so: LIBS := $(LIBS)
$(obj).target/mod_spdy/libmod_spdy.so: TOOLSET := $(TOOLSET)
$(obj).target/mod_spdy/libmod_spdy.so: $(OBJS) $(obj).target/mod_spdy/libspdy_apache.a $(obj).target/base/libbase.a $(obj).target/net/libspdy.a $(obj).target/mod_spdy/libspdy_common.a $(obj).target/base/libbase_static.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/third_party/chromium/src/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/net/libinstaweb_util.a $(obj).target/third_party/zlib/libchrome_zlib.a FORCE_DO_CMD
	$(call do_cmd,solink_module)

all_deps += $(obj).target/mod_spdy/libmod_spdy.so
# Add target alias
.PHONY: mod_spdy
mod_spdy: $(builddir)/libmod_spdy.so

# Copy this to the executable output path.
$(builddir)/libmod_spdy.so: TOOLSET := $(TOOLSET)
$(builddir)/libmod_spdy.so: $(obj).target/mod_spdy/libmod_spdy.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/libmod_spdy.so
# Short alias for building this executable.
.PHONY: libmod_spdy.so
libmod_spdy.so: $(obj).target/mod_spdy/libmod_spdy.so $(builddir)/libmod_spdy.so

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/libmod_spdy.so

