# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := spdy_apache_test
DEFS_Debug := \
	'-D_LARGEFILE64_SOURCE' \
	'-DHAVE_CONFIG_H' \
	'-DLINUX=2' \
	'-D_REENTRANT' \
	'-D_GNU_SOURCE' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	 \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-std=gnu++0x \
	-fPIC \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := \
	-Ithird_party/chromium/src \
	-I. \
	-Ithird_party/apache/httpd/src/include \
	-Ithird_party/apache/httpd/src/os/unix \
	-Ithird_party/apache/httpd/gen/arch/linux/x64/include \
	-Ithird_party/apache/apr/src/include \
	-Ithird_party/apache/apr/src/include/arch/unix \
	-Ithird_party/apache/apr/gen/arch/linux/x64/include \
	-Ithird_party/apache/aprutil/src/include \
	-Ithird_party/apache/aprutil/gen/arch/linux/x64/include \
	-Itesting/gmock/include \
	-I$(obj)/gen \
	-Itesting/gtest/include

DEFS_Release := \
	'-D_LARGEFILE64_SOURCE' \
	'-DHAVE_CONFIG_H' \
	'-DLINUX=2' \
	'-D_REENTRANT' \
	'-D_GNU_SOURCE' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := \
	 \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-std=gnu++0x \
	-fPIC \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := \
	-Ithird_party/chromium/src \
	-I. \
	-Ithird_party/apache/httpd/src/include \
	-Ithird_party/apache/httpd/src/os/unix \
	-Ithird_party/apache/httpd/gen/arch/linux/x64/include \
	-Ithird_party/apache/apr/src/include \
	-Ithird_party/apache/apr/src/include/arch/unix \
	-Ithird_party/apache/apr/gen/arch/linux/x64/include \
	-Ithird_party/apache/aprutil/src/include \
	-Ithird_party/apache/aprutil/gen/arch/linux/x64/include \
	-Itesting/gmock/include \
	-I$(obj)/gen \
	-Itesting/gtest/include

OBJS := \
	$(obj).target/$(TARGET)/mod_spdy/apache/filters/http_to_spdy_filter_test.o \
	$(obj).target/$(TARGET)/mod_spdy/apache/filters/server_push_filter_test.o \
	$(obj).target/$(TARGET)/mod_spdy/apache/filters/spdy_to_http_filter_test.o \
	$(obj).target/$(TARGET)/mod_spdy/apache/id_pool_test.o \
	$(obj).target/$(TARGET)/mod_spdy/apache/pool_util_test.o \
	$(obj).target/$(TARGET)/mod_spdy/apache/sockaddr_util_test.o \
	$(obj).target/$(TARGET)/mod_spdy/apache/testing/dummy_util_filter.o \
	$(obj).target/$(TARGET)/mod_spdy/apache/testing/spdy_apache_test_main.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/mod_spdy/libspdy_apache.a $(obj).target/mod_spdy/libspdy_common_testing.a $(obj).target/build/mod_spdy_version_header.stamp $(obj).target/testing/libgtest.a $(obj).target/third_party/apache/apr/libapr.a $(obj).target/third_party/apache/aprutil/libaprutil.a $(obj).target/mod_spdy/libspdy_common.a $(obj).target/base/libbase.a $(obj).target/base/libbase_static.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/third_party/chromium/src/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/build/lastchange.stamp $(obj).target/net/libinstaweb_util.a $(obj).target/net/libspdy.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/third_party/apache/httpd/include.stamp $(obj).target/third_party/apache/apr/include.stamp $(obj).target/third_party/apache/aprutil/include.stamp $(obj).target/testing/libgmock.a $(obj).target/testing/gtest_prod.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := \
	-pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	-lrt \
	-ldl

$(builddir)/spdy_apache_test: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/spdy_apache_test: LIBS := $(LIBS)
$(builddir)/spdy_apache_test: LD_INPUTS := $(OBJS) $(obj).target/mod_spdy/libspdy_apache.a $(obj).target/mod_spdy/libspdy_common_testing.a $(obj).target/testing/libgtest.a $(obj).target/third_party/apache/apr/libapr.a $(obj).target/third_party/apache/aprutil/libaprutil.a $(obj).target/mod_spdy/libspdy_common.a $(obj).target/base/libbase.a $(obj).target/base/libbase_static.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/third_party/chromium/src/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/net/libinstaweb_util.a $(obj).target/net/libspdy.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/testing/libgmock.a
$(builddir)/spdy_apache_test: TOOLSET := $(TOOLSET)
$(builddir)/spdy_apache_test: $(OBJS) $(obj).target/mod_spdy/libspdy_apache.a $(obj).target/mod_spdy/libspdy_common_testing.a $(obj).target/testing/libgtest.a $(obj).target/third_party/apache/apr/libapr.a $(obj).target/third_party/apache/aprutil/libaprutil.a $(obj).target/mod_spdy/libspdy_common.a $(obj).target/base/libbase.a $(obj).target/base/libbase_static.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/third_party/chromium/src/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/net/libinstaweb_util.a $(obj).target/net/libspdy.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/testing/libgmock.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/spdy_apache_test
# Add target alias
.PHONY: spdy_apache_test
spdy_apache_test: $(builddir)/spdy_apache_test

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/spdy_apache_test

